use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StudioSlot {
    Piano,
    Seat,
    Shelf,
    Decor,
    Room,
    Theme,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct StudioItem {
    pub id: &'static str,
    pub name: &'static str,
    pub description: &'static str,
    pub slot: StudioSlot,
    pub price: u64,
    pub unlock_rank: u32,
}

pub fn catalog() -> Vec<StudioItem> {
    use StudioSlot::*;
    [
        (
            "piano-digital",
            "First keys",
            "A simple electric piano. Every practice room starts somewhere.",
            Piano,
            0,
            1,
        ),
        (
            "piano-upright",
            "Walnut upright",
            "Warm wood and a familiar acoustic silhouette.",
            Piano,
            150,
            2,
        ),
        (
            "piano-baby-grand",
            "Baby grand",
            "A little more room for a growing repertoire.",
            Piano,
            500,
            3,
        ),
        (
            "piano-concert-grand",
            "Concert grand",
            "The centerpiece of your dream practice room.",
            Piano,
            1200,
            5,
        ),
        (
            "seat-box",
            "Humble beginnings",
            "The cardboard box you started with.",
            Seat,
            0,
            1,
        ),
        (
            "seat-stool",
            "Oak stool",
            "Your first proper place at the keyboard.",
            Seat,
            50,
            1,
        ),
        (
            "seat-bench",
            "Piano bench",
            "A classic bench in dark walnut.",
            Seat,
            150,
            2,
        ),
        (
            "seat-tufted",
            "Tufted bench",
            "A comfortable finishing touch for the long journey.",
            Seat,
            400,
            4,
        ),
        (
            "shelf-none",
            "Open wall",
            "Keep a little breathing room.",
            Shelf,
            0,
            1,
        ),
        (
            "shelf-oak",
            "Score shelf",
            "A home for the music you return to.",
            Shelf,
            75,
            1,
        ),
        (
            "shelf-library",
            "Music library",
            "A whole wall for a lifetime of music.",
            Shelf,
            350,
            3,
        ),
        (
            "decor-none",
            "Quiet space",
            "Nothing extra, just the music.",
            Decor,
            0,
            1,
        ),
        (
            "decor-plant",
            "Studio fern",
            "Something green beside the keys.",
            Decor,
            25,
            1,
        ),
        (
            "decor-lamp",
            "Reading light",
            "A warm pool of light for evening practice.",
            Decor,
            75,
            1,
        ),
        (
            "decor-table",
            "Walnut side table",
            "A place for a pencil, a notebook and the next idea.",
            Decor,
            100,
            1,
        ),
        (
            "decor-art",
            "Abstract study",
            "A framed composition for your studio wall.",
            Decor,
            200,
            2,
        ),
        (
            "decor-sculpture",
            "Resonance sculpture",
            "A small celebration of the time you have put in.",
            Decor,
            600,
            4,
        ),
        (
            "room-starter",
            "First room",
            "An open room with space to grow.",
            Room,
            0,
            1,
        ),
        (
            "room-oak",
            "Oak studio",
            "Warm timber and a softer afternoon light.",
            Room,
            250,
            2,
        ),
        (
            "room-loft",
            "City loft",
            "Tall windows, quiet evenings, your own corner of the city.",
            Room,
            750,
            4,
        ),
        (
            "room-conservatory",
            "Garden room",
            "Practice among the light and greenery.",
            Room,
            1500,
            6,
        ),
        (
            "theme-graphite",
            "Graphite",
            "The original neutral dark palette.",
            Theme,
            0,
            1,
        ),
        (
            "theme-sand",
            "Warm ivory",
            "A warm, paper-inspired studio palette.",
            Theme,
            100,
            1,
        ),
        (
            "theme-midnight",
            "Midnight",
            "A deep blue palette for after-hours practice.",
            Theme,
            250,
            2,
        ),
        (
            "theme-forest",
            "Forest",
            "A quiet green palette inspired by the outdoors.",
            Theme,
            400,
            3,
        ),
    ]
    .into_iter()
    .map(
        |(id, name, description, slot, price, unlock_rank)| StudioItem {
            id,
            name,
            description,
            slot,
            price,
            unlock_rank,
        },
    )
    .collect()
}
